### ISSUE TITLE
Perceptual brightness is squared due to being handled twice

### ISSUE THREAD

**Issue by gri573** [Cyxo/ASCII-Art-Shader#2]
Using letters with different sizes / areas as it is done in ASCII art already controls the brightness of the image, Giving those letters the original colour (which includes the original brightness) results in effectively squaring the brightness, leading to high contrast and a rather dark image. A possible fix for this would be to insert the line `col /= max(col.r, max(col.g, col.b));` after line 125 of final.fsh

**Comment by Cyxo** [comment]
Hello,

Thank you for your suggestion!
At the time I made this shader, I thought that artificial brightness had to be added after rendering the characters to make it look brighter. But you're right, the problem was that the brightness was handled twice.

I released a new version with your line (and removed the artificial brightness and saturation which in fact made the colors look dull).
